
["Ω"]
type="Element{:Tri3}"
"𝓒".tag="Ω"
"𝓖".type="TriGI3"
"𝓖"."𝝭"="∇𝝭"

["Γᵗ"]
type="Element{:Seg2}"
"𝓒".tag="Γᵗ"
"𝓖".type="SegGI2"
"𝓖"."𝝭"="𝝭"

["Γᵍ"]
type="Element{:Seg2}"
"𝓒".tag="Γᵍ"
"𝓖".type="SegGI2"
"𝓖"."𝝭"="𝝭"

["Ω̄"]
type="Element{:Tri3}"
"𝓒".tag="Ω"
"𝓖".type="TriGI6"
"𝓖"."𝝭"="∇𝝭"